# GitHub repository SSH URL
github.repo.url=git@github.com:gdncomm/trade-in-catalog.git

# Jira ticket URL
jira.ticket.url=https://gdncomm.atlassian.net/browse/OMG-3672

# AI agent type : (claude | codex | cursor)
# AI model type :
# - claude : opus, sonnet, haiku
# - codex : gpt-5, gpt-5-codex
# - cursor : auto, composer-1.5, composer-1, gpt-5.3-codex, gpt-5.3-codex-low, gpt-5.3-codex-high, gpt-5.3-codex-xhigh, gpt-5.3-codex-fast, gpt-5.3-codex-low-fast, gpt-5.3-codex-high-fast, gpt-5.3-codex-xhigh-fast, gpt-5.3-codex-spark-preview, gpt-5.2, gpt-5.2-codex, gpt-5.2-codex-high, gpt-5.2-codex-low, gpt-5.2-codex-xhigh, gpt-5.2-codex-fast, gpt-5.2-codex-high-fast, gpt-5.2-codex-low-fast, gpt-5.2-codex-xhigh-fast, gpt-5.1-codex-max, gpt-5.1-codex-max-high, opus-4.6-thinking, gpt-5.2-high, opus-4.6, opus-4.5, opus-4.5-thinking, sonnet-4.6, sonnet-4.6-thinking, sonnet-4.5, sonnet-4.5-thinking, gpt-5.1-high, gemini-3.1-pro, gemini-3-pro, gemini-3-flash, gpt-5.1-codex-mini, grok, kimi-k2.5

ai.plan.agent=cursor
ai.plan.model=gpt-5.3-codex

ai.implementation.agent=cursor
ai.implementation.model=gpt-5.3-codex

replan.timeout.duration=3600
replan.timeout.decision=start

# Base branch, target branch for PR.
branch.base=release/1.88.0

# Working branch where AI will work.
branch.work=feature-agent/OMG-3672

# Jenkins build url
jenkins.build.url=https://jenkins-build-ci-2.gdn-app.com/job/GitHub/job/gdncomm/job/GDN/job/HIC/job/trade-in-catalog/

# Max Retry Build
max.retry.count=5

# Optional: Existing PR URL. If provided, source/destination branches are derived from PR
pr.url=
